AllCops:
  Exclude:
    - 'db/schema.rb'
  Rails:
    Enabled: true

HandleExceptions:
  Exclude:
    - 'bin/*'

AsciiComments:
  Exclude:
    - '**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/AlignHash:
  EnforcedHashRocketStyle: key

Style/ClassAndModuleChildren:
  Exclude:
    - 'config/routes.rb'

Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'app/models/**/*'
    - 'app/helpers/**/*'
    - 'app/mailers/**/*'
    - 'app/controllers/**/*'
    - 'config/application.rb'
    - 'config/routes.rb'
    - 'lib/**/*'
    - 'config/initializers/**/*'
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Metrics/AbcSize:
  Max: 18
  Exclude:
    - 'db/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'Gemfile'
    - 'config/deploy.rb'
    - 'db/**/*'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/environments/production.rb'
