development:
  adapter: postgresql
  encoding: UTF8
  database: ssb_dev
  username: ssb
  password: 123ssb
  host: localhost
  pool: 25

test:
  adapter: postgresql
  encoding: UTF8
  database: ssb_test
  username: ssb
  password: 123ssb
  host: localhost
  pool: 25
